spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/user-details
    password: ParkView0502
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
logging:
  level:
    org:
      springframework:
        security: TRACE